FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3 python3-pip openssh-client \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install ansible

WORKDIR /ansible
CMD ["tail", "-f", "/dev/null"]